model:
  name: "SimpleCNN"
  dropout_rate: 0.5

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 30
  optimizer: "adam"
  scheduler: "step"
  step_size: 10
  gamma: 0.1

data:
  augmentation: false
  val_split: 0.2

experiment:
  name: "baseline_simple_cnn"
  save_path: "../experiments/"