experiments:
  - model:
      name: "DeepCNN"
      dropout_rate: 0.5
    training:
      batch_size: 32
      learning_rate: 0.001
      epochs: 50
      optimizer: "adam"
    data:
      augmentation: true
    experiment:
      name: "deep_cnn_augmented"
  
  - model:
      name: "ResNetFER"
      dropout_rate: 0.5
    training:
      batch_size: 32
      learning_rate: 0.001
      epochs: 50
      optimizer: "adam"
    experiment:
      name: "resnet_fer_baseline"